SELECT
  COUNT(CASE
    WHEN BIN_CODE LIKE 'N%' AND BIN_CODE NOT LIKE 'N2%' THEN 1
  END) AS 常溫一期,

  COUNT(CASE
    WHEN BIN_CODE LIKE 'N2%' THEN 1
  END) AS 常溫二期,

  COUNT(CASE
    WHEN BIN_CODE LIKE 'N%' THEN 1
  END) AS 常溫當天總產能
FROM ITFC_MES_UPLOAD_STATUS_TB
WHERE TYPE = 4
  AND BOX_BATT <> 'NANANANANANA'
   AND create_date >= '2026-03-03 00:00:00'
   AND create_date < '2026-03-03 12:00:00'

   