WITH FilteredData AS (
  SELECT BOX_BATT, K_value, ID, TRY_CONVERT(date, CREATE_DATE) AS conv_date
  FROM HTBI_K_Value_MapperType_V
  WHERE TRY_CONVERT(date, CREATE_DATE) IS NOT NULL
)
SELECT BOX_BATT, K_value, ID
FROM FilteredData
WHERE conv_date >= ('2024-8-26')
  AND ID >= 2046268
ORDER BY ID desc


SELECT TOP 1 *
FROM HTBI_K_Value_MapperType_V
ORDER BY ID DESC;

SELECT  *
FROM HTBI_K_Value_MapperType_V
WHERE BOX_BATT like 'MW2009A43613';

 